# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
julia:
  - nightly
  - 1.4

codecov: true
coveralls: true

script:
  - xvfb-run julia --project -e 'using Pkg; Pkg.test(coverage=true)'
