# Documentation: http://docs.travis-ci.com/user/languages/julia/
#                https://github.com/JuliaLang/Example.jl/blob/master/.travis.yml
## 
language: julia

coveralls: true

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'

script:
  - xvfb-run julia --project --code-coverage -e 'using Pkg; Pkg.test(coverage=true)'
